version: "3.1"

services:
  typeorm-poc:
    build:
      context: ./
    restart: on-failure
    environment:
      NODE_ENV: dev
      PG_USER: postgres
      PG_PWD: postgres
      DB_HOST: postgres
      DB_NAME: typeorm-poc
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]

  postgres:
    image: postgres:10.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  node_modules:
  postgres:
